base-url: /blog

# Site setting
description: "Place to write-down"

# Sidebar settings
sidebar: true  #添加侧边栏
sidebar-about-description:"Place to write-down"

# Featured Tags
featured-tags: true  
featured-condition-size: 1 

theme: jekyll-theme-minimal